name: Bundle Deployment for mlops-project-stijn Staging
'on':
  push:
    branches:
    - main
  workflow_dispatch: null
permissions: write-all
defaults:
  run:
    working-directory: ./mlops_project_stijn
env:
  DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}
jobs:
  staging:
    concurrency: mlops-project-stijn-staging-bundle-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: databricks/setup-cli@main
    - name: Validate Bundle For Staging Environment
      id: validate
      run: 'databricks bundle validate -t staging

        '
    - name: Deploy Bundle to Staging Environment
      id: deploy
      run: 'databricks bundle deploy -t staging

        '
